name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:

    runs-on: macos-13
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Run unit tests
        env:
          TEST_USER_ID_1: ${{ secrets.TEST_USER_ID_1 }}
          TEST_APP_ID_1: ${{ secrets.TEST_APP_ID_1 }}
          TEST_USER_ID_2: ${{ secrets.TEST_USER_ID_2 }}
          TEST_APP_ID_2: ${{ secrets.TEST_APP_ID_2 }}
        run: flutter test --pub test/test.dart --coverage

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 70
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
