name: Flutter Test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  run_tests:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run unit tests
        env:
          TEST_USER_ID_1: ${{ secrets.TEST_USER_ID_1 }}
          TEST_APP_ID_1: ${{ secrets.TEST_APP_ID_1 }}
          TEST_USER_ID_2: ${{ secrets.TEST_USER_ID_2 }}
          TEST_APP_ID_2: ${{ secrets.TEST_APP_ID_2 }}
        run: flutter test test/test.dart